turtlebot3: #namespace

    task_and_robot_environment_name: 'TurtleBot3World-v0'
    ros_ws_abspath: "/home/danielbugelnig/mobile_robot_navigation"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #dqn parameters
    gamma: 0.999
    epsilon_start: 0.7
    epsilon_end: 0.02
    epsilon_decay: 300
    n_episodes: 3000 #500  
    target_update: 20
    batch_size: 256

    running_step: 0.06 # Time for each step

